import type { HardwarePreset, Harness, ModelConfig } from "./types";

export const PRESETS: HardwarePreset[] = [
  {
    id: "mba-m2-16",
    name: "MacBook Air M2",
    subtitle: "16 GB unified",
    chip: "Apple M2",
    cores: 8,
    ramGb: 16,
    gpuLabel: "Metal / unified",
    gpuVramGb: 16,
    bandwidthGBs: 100,
    kind: "apple",
  },
  {
    id: "mbp-m4-max-48",
    name: "MacBook Pro M4 Max",
    subtitle: "48 GB unified",
    chip: "Apple M4 Max",
    cores: 16,
    ramGb: 48,
    gpuLabel: "Metal / unified",
    gpuVramGb: 48,
    bandwidthGBs: 546,
    kind: "apple",
  },
  {
    id: "gaming-64-4090",
    name: "Gaming PC + RTX",
    subtitle: "64 GB · RTX 4090",
    chip: "Ryzen 9 7950X",
    cores: 16,
    ramGb: 64,
    gpuLabel: "RTX 4090",
    gpuVramGb: 24,
    bandwidthGBs: 1008,
    kind: "nvidia",
  },
  {
    id: "cloud-a100-80",
    name: "Cloud A100",
    subtitle: "80 GB HBM2e",
    chip: "AMD EPYC · A100",
    cores: 32,
    ramGb: 128,
    gpuLabel: "NVIDIA A100",
    gpuVramGb: 80,
    bandwidthGBs: 1935,
    kind: "cloud",
  },
];

export const MODELS: ModelConfig[] = [
  {
    id: "gemma-4-e2b-q4",
    name: "Gemma 4 E2B",
    family: "Gemma 4",
    params: "5B dense",
    quant: "4-bit QAT",
    quantKind: "qat",
    bits: 4,
    contextK: 50,
    weightGb: 4.6,
    intelligence: 62,
    baseAccuracy: 88,
    speculative: false,
    vision: true,
    moe: false,
  },
  {
    id: "lfm25-2.6b-q4",
    name: "Liquid LFM2.5",
    family: "LFM",
    params: "2.6B",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 32,
    weightGb: 1.8,
    intelligence: 48,
    baseAccuracy: 72,
    speculative: true,
    vision: false,
    moe: false,
  },
  {
    id: "qwen35-4b-q4",
    name: "Qwen3.5 4B",
    family: "Qwen",
    params: "4B",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 32,
    weightGb: 2.7,
    intelligence: 58,
    baseAccuracy: 76,
    speculative: true,
    vision: false,
    moe: false,
  },
  {
    id: "qwen35-4b-q8",
    name: "Qwen3.5 4B",
    family: "Qwen",
    params: "4B",
    quant: "Q8_0",
    quantKind: "ptq",
    bits: 8,
    contextK: 32,
    weightGb: 4.5,
    intelligence: 60,
    baseAccuracy: 90,
    speculative: true,
    vision: false,
    moe: false,
  },
  {
    id: "phi4-mini-q4",
    name: "Phi-4 Mini",
    family: "Phi",
    params: "3.8B",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 16,
    weightGb: 2.4,
    intelligence: 55,
    baseAccuracy: 78,
    speculative: true,
    vision: false,
    moe: false,
  },
  {
    id: "llama4-scout-8b-q4",
    name: "Llama 4 Scout",
    family: "Llama",
    params: "8B",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 64,
    weightGb: 5.1,
    intelligence: 70,
    baseAccuracy: 80,
    speculative: true,
    vision: true,
    moe: false,
  },
  {
    id: "glm47-9b-q4",
    name: "GLM 4.7 9B",
    family: "GLM",
    params: "9B",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 32,
    weightGb: 5.8,
    intelligence: 74,
    baseAccuracy: 81,
    speculative: true,
    vision: false,
    moe: false,
  },
  {
    id: "ds-v4-14b-q4",
    name: "DeepSeek V4 Distill",
    family: "DeepSeek",
    params: "14B",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 64,
    weightGb: 8.9,
    intelligence: 82,
    baseAccuracy: 83,
    speculative: true,
    vision: false,
    moe: false,
  },
  {
    id: "mistral-small-24b-q4",
    name: "Mistral Small",
    family: "Mistral",
    params: "24B",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 32,
    weightGb: 14.2,
    intelligence: 86,
    baseAccuracy: 84,
    speculative: true,
    vision: false,
    moe: false,
  },
  {
    id: "qwen36-35b-a3b-q4",
    name: "Qwen3.6 35B-A3B",
    family: "Qwen",
    params: "35B-A3B MoE",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 64,
    weightGb: 20.4,
    intelligence: 90,
    baseAccuracy: 85,
    speculative: false,
    vision: false,
    moe: true,
  },
  {
    id: "qwen36-35b-a3b-q8",
    name: "Qwen3.6 35B-A3B",
    family: "Qwen",
    params: "35B-A3B MoE",
    quant: "Q8_0",
    quantKind: "ptq",
    bits: 8,
    contextK: 32,
    weightGb: 38.0,
    intelligence: 93,
    baseAccuracy: 93,
    speculative: false,
    vision: false,
    moe: true,
  },
  {
    id: "kimi-k2-70b-q4",
    name: "Kimi K2 Distill",
    family: "Kimi",
    params: "70B",
    quant: "Q4_K_M",
    quantKind: "ptq",
    bits: 4,
    contextK: 32,
    weightGb: 42.0,
    intelligence: 96,
    baseAccuracy: 88,
    speculative: false,
    vision: false,
    moe: false,
  },
];

export const HARNESSES: Harness[] = [
  { id: "pi", name: "Pi", hint: "Local-first agent", configHint: "~/.pi/config.toml" },
  { id: "opencode", name: "OpenCode", hint: "TUI coding agent", configHint: "opencode.json" },
  { id: "claude-code", name: "Claude Code", hint: "Anthropic-compatible", configHint: ".claude/settings.json" },
  { id: "codex", name: "Codex", hint: "OpenAI-compatible", configHint: "~/.codex/config.toml" },
  { id: "hermes", name: "Hermes", hint: "Nous harness", configHint: "hermes.yaml" },
  { id: "cline", name: "Cline", hint: "VS Code agent", configHint: "cline.customModels" },
  { id: "oh-my-pi", name: "Oh My Pi", hint: "Pi variant", configHint: "~/.oh-my-pi/config.toml" },
  { id: "openclaw", name: "OpenClaw", hint: "Open harness", configHint: "openclaw.json" },
];

export const AXIS_META = [
  { key: "speed", label: "Speed", hint: "Estimated tok/s on this machine" },
  { key: "accuracy", label: "Accuracy", hint: "Quantization quality for tool calls" },
  { key: "intelligence", label: "Intelligence", hint: "Raw model capability" },
  { key: "memory", label: "Memory", hint: "How easily the config fits" },
] as const;
